name: Test the Action

on:
  schedule:
    - cron: '0 18 * * *' # Runs at 18:00 UTC every day, 02:00 UTC+8

jobs:
  algolia:
    runs-on: ubuntu-latest
    name: algolia-crawler
    steps:
      - name: crawling
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          # needs to be inside $GITHUB_WORKSPACE from actions/checkout step
          file: docs/algolia-config-hope.json
